# Generated by Django 5.1.4 on 2025-01-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escola', '0002_matriculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriculo',
            new_name='Matricula',
        ),
    ]
